### ISSUE TITLE
微博超话失败问题

### ISSUE THREAD

**Issue by o1xhack** [toulanboy/scripts#1]
1. 首先做了清理 cookie，提示清理完成后改为了 false
2.去第一个帐号关注了新的超话，签到 得到图片中下面那条通知
3.去第二个帐号关注+签到，没收到任何通知
4.手动运行脚本得到图片中上方提示

![IMG_1510](https://user-images.githubusercontent.com/10677990/85240563-759bfe80-b3ed-11ea-8694-e77d90cad121.jpg)

**Comment by toulanboy** [comment]
来信收到。感谢用issue描述清楚你的情况。

基于目前你提供的信息，可能是因为你第1个账号没有获取关注列表。建议你重新打开一次关注，提示获取关注列表成功后就可以了。
请注意：务必点击【底部栏】的”我的“，然后再点上面的”关注“。才能触发。


如若还不行，请在清空ck后，确保delete_cookie置为false后。重开app，进行获取流程就行。

**Comment by o1xhack** [comment]
> 来信收到。感谢用issue描述清楚你的情况。
> 
> 基于目前你提供的信息，可能是因为你第1个账号没有获取关注列表。建议你重新打开一次关注，提示获取关注列表成功后就可以了。
> 请注意：务必点击【底部栏】的”我的“，然后再点上面的”关注“。才能触发。
> 
> 如若还不行，请在清空ck后，确保delete_cookie置为false后。重开app，进行获取流程就行。

感谢。完全不知道是要在【底部栏】的”我的“，然后再点上面的”关注“。
一直不知道点进去超话下面的tab都变了。。。
现在都获取成功了，就是需要拼图验证，看来得多签到一下- -
