### ISSUE TITLE
IT之家新闻流还有广告，我提供下新闻流地址

### ISSUE THREAD

**Issue by ChuHuaiJin** [toulanboy/scripts#10]
如题，目前IT之家新闻流还有广告，我提供下新闻流地址

https://api.ithome.com/json/listpage/news/fed70c5e0b9e57e299a350db48458826

<sub>Sent from <a href="https://apps.apple.com/cn/app/id1314212521">PPHub</a></sub>

**Comment by toulanboy** [comment]
**感谢**。已更新。

同时，加上了一键配置的conf。建议使用conf。

**Comment by ChuHuaiJin** [comment]
> **感谢**。已更新。
> 
> 同时，加上了一键配置的conf。建议使用conf。

感谢大佬出手相救
