### ISSUE TITLE
清空Cookie相关问题

### ISSUE THREAD

**Issue by IMe213** [toulanboy/scripts#13]
账号需要重新获取Cookie，然后清空环境重新获取Cookie成功后，账号1依然失败，成功获取的为账号2，现在尝试再次清空环境，一直处于失败的状态。
![314E02EB-162F-4FD5-B3AD-1893AD036C9C](https://user-images.githubusercontent.com/59537689/111952433-1c016580-8b20-11eb-89d4-3fb0e174aff9.jpeg)

**Comment by toulanboy** [comment]
hello，目前判断是你没有正确执行清空cookie的步骤。建议尝试以下流程:
1，在boxjs里面打开清空cookie开关。
2，手动跑一次脚本。
3，打开获取cookie的rewrite。
4，执行获取cookie步骤。
5，关闭获取cookie的rewrite。

如果还有问题，欢迎继续反馈。

**Comment by IMe213** [comment]
已解决，感谢！
