### ISSUE TITLE
Quantumult X 环境下 BoxJs 内运行微博签到错误

### ISSUE THREAD

**Issue by chouchoui** [toulanboy/scripts#14]
Quantumult X 环境下 BoxJs 内直接运行微博签到会报错：`TypeError: Attempted to assign to readonly property.`

https://github.com/toulanboy/scripts/blob/d21d633af87fa4d315e9fbb47cd021032ea9d2e0/weibo/weibotalk.js#L51
需要将这一行内容修改为
```js
const $ = new Env("微博超话")
```

**Comment by toulanboy** [comment]
@chouchoui 同学你好，感谢指正。已更新。
