### ISSUE TITLE
反馈一条过滤IT之家双十一广告的复写

### ISSUE THREAD

**Issue by ArriettyQAQ** [toulanboy/scripts#20]
这是“资讯”列表里插入的双十一红包图片广告

https://api.zuihuimai.com/static/s11/2022-1111/hongbao.html

具体复写如下，目前测试有效，配合你的IT之家去广告脚本完美无广告。

另，感谢你的IT之家去广告脚本。

[Rewrite]
^https?:\/\/api\.zuihuimai\.com\/static\/.*\/hongbao.. reject

[MITM]
hostname = api.zuihuimai.com

这个是Loon的格式

<sub>Sent from <a href="https://apps.apple.com/cn/app/id1314212521">PPHub</a></sub>

**Comment by toulanboy** [comment]
谢谢反馈。目前暂时未能复现这个广告。后续再看看

**Comment by toulanboy** [comment]
谢谢反馈，已更新。
