### ISSUE TITLE
IT之家文章末尾广告

### ISSUE THREAD

**Issue by ArriettyQAQ** [toulanboy/scripts#21]
目前几乎每篇文章的底部都有这样的广告

[![IMG_0354](https://i.im.ge/2022/11/11/SoB0pz.IMG-0354.png)](https://im.ge/i/SoB0pz)
[![IMG_0355](https://i.im.ge/2022/11/11/SoBiCS.IMG-0355.png)](https://im.ge/i/SoBiCS)
[![IMG_0356](https://i.im.ge/2022/11/11/SoBh7y.IMG-0356.png)](https://im.ge/i/SoBh7y)
[![IMG_0357](https://i.im.ge/2022/11/11/SoBLGJ.IMG-0357.png)](https://im.ge/i/SoBLGJ)

**Comment by toulanboy** [comment]
谢谢反馈，不影响阅读，暂不跟进。
