### ISSUE TITLE
改进下无库存问题

### ISSUE THREAD

**Issue by photonmang** [toulanboy/scripts#3]
无库存的是否应该不再提醒。

**Comment by toulanboy** [comment]
麻烦给个具体的商品链接

**Comment by toulanboy** [comment]
@photonmang 麻烦给个具体的商品链接。

**Comment by photonmang** [comment]
https://item.m.jd.com/product/100013264128.html?wxa_abtest=o&utm_source=iosapp&utm_medium=appshare&utm_campaign=t_335139774&utm_term=CopyURL&ad_od=share

这个链接，显示已无货设定599价格就会一直提醒

**Comment by toulanboy** [comment]
@photonmang 收到，这两天有空处理。有可能无法检测这个，因为库存是和地区相关的。
