### ISSUE TITLE
微博超话 cookie 保存为同一账号问题。

### ISSUE THREAD

**Issue by o1xhack** [toulanboy/scripts#6]
使用了 boxjs 清理了cookie。

1.进行cookie 获取，按照之前的方法，两个帐号都显示获取到了 账号2.

2. 想要单独运行脚本，报错：`An exception was catched while evaluate script Untitled: Error: 不支持的URL. Line number 192, column:32`

使用的 surge。如需更多测试请告诉我~

**Comment by toulanboy** [comment]
使用BoxJS打开开关后，有去跑1次脚本吗？
